[project]
name = "new-flask"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "flask>=3.1.0",
    "flask-session>=0.8.0",
    "pymysql>=1.1.1",
    "sqlalchemy>=2.0.40",
    "werkzeug>=3.1.3",
]
